{
  "error": {
    "status": 400,
    "body": {
      "message": "An error occurred while trying to update the record. Please try again.",
      "statusCode": 400,
      "enhancedErrorType": "RecordError",
      "output": {
        "errors": [
          {
            "constituentField": null,
            "duplicateRecordError": null,
            "errorCode": "PORTAL_USER_ALREADY_EXISTS_FOR_CONTACT",
            "field": null,
            "fieldLabel": null,
            "message": "portal user already exists for contact"
          }
        ],
        "fieldErrors": {}
      },
      "id": "-1811437745"
    },
    "headers": {},
    "ok": false,
    "statusText": "Bad Request",
    "errorType": "fetchResponse"
  }
}
